name: Sample Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello world" >> build

      - name: Generate and upload build
        uses: actions/upload-artifact@v4.3.4
        with:
          path: ./build

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo I am a wizard

  deploy:
    runs-on: ubuntu-latest

    needs: test

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo I am a wizard

      - name: Download the build
        uses: actions/download-artifact@v4.1.8
              

          
